name: RSpec CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby }}'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.1 # eol
          - ruby: 3.2
          - ruby: 3.3
          - ruby: 3.4

    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rspec
        continue-on-error: ${{ matrix.allow_failure || false }}